import createEffect from '@/utils/fire_canvas'
import { stone } from '@/utils/global'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useRef } from 'react'
import styled from 'styled-components'


const DIV = styled.div`
  overflow: hidden;
.fire_wrap{
  position: fixed;
  width: 100vw;
  height: 100vh;
  vertical-align: bottom;
  z-index: -1;
}
`

export default function Demos() {
  const fire = useRef<HTMLCanvasElement | null>(null)
  useEffect(() => {
    const obj = fire.current && createEffect(fire.current)
    return () => {
      obj?.ruin()
    }
  }, [])
  return (
    <>
      <Head>
        <title>Demos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DIV>
          <canvas className='fire_wrap' ref={fire}></canvas>
        </DIV>
      </main>
    </>
  )
}
