import { stone } from '@/utils/global'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useRef } from 'react'
import styled from 'styled-components'

const DIV = styled.div`
  overflow: hidden;
  .fire_wrap{
    position: fixed;
    width: 100%;
    height: 100%;
    vertical-align: bottom;
    z-index: -1;
  }
`

export default function Demos() {
  return (
    <>
      <Head>
        <title>Demos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DIV>
          <iframe className='fire_wrap' src="https://empty.t-n.top/html/WebGL%20Fluid%20Simulation.html"></iframe>
        </DIV>
      </main>
    </>
  )
}
