import Head from 'next/head'
import { useEffect, useState } from 'react'
import styled from 'styled-components'

const DIV = styled.div`
  overflow: hidden;
  .fire_wrap{
    position: fixed;
    width: 100%;
    height: 100%;
    vertical-align: bottom;
    z-index: 0;
  }
`

export default function Game2048() {
  const [show, isShow] = useState(false)
  useEffect(() => {
    isShow(true)
  }, [])
  return (
    <>
      <Head>
        <title>Demos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DIV>
          {show && <iframe className='fire_wrap' src="https://empty.t-n.top/html/2048.html"></iframe>}
        </DIV>
      </main>
    </>
  )
}


export const getStaticProps = async (context: any) => {
  return {
    props: {}
  }
}