import LazyImage from '@/components/LazyImage'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

import style from './index.module.scss'

export default function Error() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {router.isFallback ? (<div style={{
          fontSize: '32px',
          color: 'gray',
          textAlign: 'center',
          margin: '80px auto'
        }}>loading...</div>) : (<div className={`${style['err_wrap']} ${style['wrap']}`}>
          <img className={style['img']} width="800" height="600" src='https://empty.t-n.top/pub_lic/2023_07_06/pic1688608901221777.gif' alt="404" />
          <Link href="/" className={style['back']} aria-label="back to homepage">BACK</Link>
        </div>)}
      </main>
    </>
  )
}

export const getStaticProps = async (context: any) => {
  return {
    props: {}
  }
}
