// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }


import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react'


export default function Home() {
  const [secret, setSecret] = useState('');
  const [github, setGithub] = useState('');
  const router = useRouter();
  const parseObj2queryStr = (obj: { [key: string]: any }) => {
    const data = Object.keys(obj).map(key => `${key}=${String(obj[key])}`).join('&')
    return data ? `?${data}` : ''
  }
  const parsequeryStr2Obj = (str: string) => {
    const obj: { [key: string]: string } = {}
    const data = str.split('?')[1]?.split('&').forEach((item) => {
      const [key, value] = item.split('=')
      obj[key] = value
    })
    return obj
  }

  const login = () => {
    console.log(process.env.NEXT_PUBLIC_SECRET, process.env.NEXT_PUBLIC_CLIENT_ID, location.origin)
    const par = {
      client_id: process.env.NEXT_PUBLIC_CLIENT_ID,
      // redirect_uri: location.origin,
      scope: 'repo',
    }
    // console.log(parseObj2queryStr(par));
    location.href = `https://github.com/login/oauth/authorize${parseObj2queryStr(par)}`
    // setGithub(`https://github.com/login/oauth/authorize${parseObj2queryStr(par)}`)
  }

  const queryToken = (code: any) => {
    const par = {
      url: 'https://github.com/login/oauth/access_token',
      method: 'POST',
      headers: {
        Accept: 'application/vnd.github+json',
      },
      data: {
        client_id: process.env.NEXT_PUBLIC_CLIENT_ID,
        client_secret: process.env.NEXT_PUBLIC_SECRET,
        code,
      }
    }
    fetch('https://mess.t-n.top/mess/', {
      // fetch('/github/login/oauth/access_token', {
      method: 'POST',
      body: JSON.stringify(par),
    }).then(res => res.json()).then(data => {
      console.log(data)
      data.access_token && sessionStorage.setItem('token', data.access_token);
      queryCurUser();
      router.push('/');
    })
  }
  const queryCurUser = () => {
    const par = {
      url: 'https://api.github.com/user',
      method: 'GET',
      headers: {
        Accept: 'application/vnd.github+json',
        Authorization: `token ${sessionStorage.token}`,
      },
    }
    fetch('https://mess.t-n.top/mess/', {
      method: 'POST',
      body: JSON.stringify(par),
    }).then(res => res.json()).then(data => {
      console.log(data)
      data.login && sessionStorage.setItem('userInfo', JSON.stringify(data));
    })
  }

  useEffect(() => {
    const query = parsequeryStr2Obj(router.asPath)
    if (query.code) {
      console.log(query.code);
      queryToken(query.code);
      // router.push('/');
    } else {
      if (!sessionStorage.token) return;
      queryCurUser();

    }
  }, [])
  return (
    <>
      <Head>
        <title>666</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </Head>
      <main>
        <img src="/github.svg" style={{ width: '32px' }} alt='github' onClick={login} />
        <div>
          <Link href="/about">关于我们</Link>
        </div>
      </main>
    </>
  )
}

