import { editArtical, listArtical } from '@/req/main'
import { Artical } from '@/types/global'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import BlogCreator from '../components/creator'
import { useRouter } from 'next/router'

type Props = {
  artical: Artical
}

export default function BlogEdit() {
  const [artical, setArtical] = useState<Artical>()
  const router = useRouter()
  useEffect(() => {
    const { number } = router.query
    if(number) {
      listArtical(+number).then(res => {
        res?.data && setArtical(res.data)
      })
    }
  }, [router.query])
  return (
    <>
      <Head>
        <title>edit blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {artical && <BlogCreator artical={artical} onSubmit={editArtical} />}
      </main>
    </>
  )
}
