name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: out
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          run: npm install && npm run build
