name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v3
      with:
        path: dev
    - name: buid
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: out
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          clean: true
