name: GitHub Actions Build and Deploy Demo
on: 
  push: 
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
    - run: npm i
    - name: build
      run: npm run build
      env: 
        NEXT_PUBLIC_CLIENT_ID: ${{ vars.NEXT_PUBLIC_CLIENT_ID }}
        NEXT_PUBLIC_GITHUB_USER: ${{ vars.NEXT_PUBLIC_GITHUB_USER }}
        NEXT_PUBLIC_SECRET: ${{ vars.NEXT_PUBLIC_SECRET }}
        NEXT_PUBLIC_MESS_URL: ${{ vars.NEXT_PUBLIC_MESS_URL }}
        NEXT_PUBLIC_EXTRA_URL: ${{ vars.NEXT_PUBLIC_EXTRA_URL }}
        NEXT_PUBLIC_LOADING_GIF: ${{ vars.NEXT_PUBLIC_LOADING_GIF }}
        NEXT_PUBLIC_GITHUB_ID: ${{ vars.NEXT_PUBLIC_GITHUB_ID }}
        NEXT_PUBLIC_FIXED_GITHUB_TOKEN: ${{ vars.NEXT_PUBLIC_FIXED_GITHUB_TOKEN }}
        NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
        SITE_URL: ${{ vars.SITE_URL }}
    - name: deply
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        clean: true