name: GitHub Actions Build and Deploy Demo
on: 
  push: 
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
    - run: npm i
    - name: build
      run: npm run build
      env: 
        NEXT_PUBLIC_CLIENT_ID: ${{ env.NEXT_PUBLIC_CLIENT_ID }}
        NEXT_PUBLIC_SECRET: ${{ env.NEXT_PUBLIC_SECRET }}
    - name: deply
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        clean: true