name: GitHub Actions Build and Deploy Demo
on: 
  push: 
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
    - name: buid
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        clean: true
